version: '3'
services:
  web:
    build: .
    restart: always
    tty: true
    stdin_open: true
    command: ash -c "rm -f /app/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=db
    depends_on:
      - db
    volumes:
      - ./:/app:cached

  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 15432:5432
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
