version: '3'
services:
  web:
    build: .
    restart: always
    tty: true
    stdin_open: true
    command: ash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=db
    depends_on:
      - db
    volumes:
      - "./:/app"

  db:
    restart: always
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=
    ports:
      - 15432:5432

volumes:
   ? db
